# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Chris Paxton
tagline:          'Robotics: Learning, Planning, and Collaborating with Humans'
description:      'PhD Candidate at Johns Hopkins University'
url:              https://cpaxton.github.io
baseurl:          /

author:
  name:           'Chris Paxton'
  url:            https://twitter.com/chris_j_paxton

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/cpaxton/

youtube:
  url:            https://www.youtube.com/channel/UCg5x0AKmVywo7OehotMLgeg
