name: Chris Paxton
markdown: redcarpet

# More info here
title:            Chris Paxton
description:      "Artificial Common Sense"
logo:             logo.png
disqus_shortname: cpaxton
share:            true
dropcap:	  true
url:        	  https://cpaxton.github.io
baseurl:          https://cpaxton.github.io/


